apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ required "mysql.rootPassword is required" .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ required "mysql.password is required" .Values.mysql.password | quote }}
