apiVersion: v1
kind: Secret
metadata:
  name: auth
type: Opaque
stringData:
  JWT_SECRET: {{ required "auth.jwtSecret is required" .Values.auth.jwtSecret | quote }}
  RABBITMQ_USER: {{ .Values.auth.rabbitmqUser | quote }}
  RABBITMQ_PASSWORD: {{ required "auth.rabbitmqPassword is required" .Values.auth.rabbitmqPassword | quote }}
